import "@/modules/app/UI/styles/globals.css";
import type { Metadata } from "next";
import type { ReactNode } from "react";

import Nav from "@/modules/app/UI/components/nav/nav.component";
import { ContainerCustom } from "@/modules/app/UI/components/tags";
import { ThemeProvider } from "@/modules/app/UI/provider/theme.provider";
import { AuthUserProvider } from "@/modules/auth/UI/providers/auth-user.provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: ReactNode;
}>): ReactNode => {
	return (
		<html suppressHydrationWarning lang="es">
			<body>
				<ThemeProvider
					disableTransitionOnChange
					enableSystem
					attribute="class"
					defaultTheme="system"
				>
					<AuthUserProvider>
						<header>
							<Nav />
						</header>
						<ContainerCustom>{children}</ContainerCustom>
					</AuthUserProvider>
				</ThemeProvider>
			</body>
		</html>
	);
};

export default RootLayout;
