import "@/modules/app/UI/styles/globals.css";
import type { Metadata } from "next";
import type { ReactNode } from "react";

import Nav from "@/modules/app/UI/components/nav/nav.component";
import ContainerCustom from "@/modules/app/UI/components/tags/container-custom.component";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: ReactNode;
}>): ReactNode => {
	return (
		<html suppressHydrationWarning lang="en">
			<body>
				<header>
					<Nav />
				</header>
				<ContainerCustom>{children}</ContainerCustom>
			</body>
		</html>
	);
};

export default RootLayout;
